// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AButton: typeof import('ant-design-vue/es')['Button']
    ADatePicker: typeof import('ant-design-vue/es')['DatePicker']
    AEmpty: typeof import('ant-design-vue/es')['Empty']
    AForm: typeof import('ant-design-vue/es')['Form']
    AFormItem: typeof import('ant-design-vue/es')['FormItem']
    AInput: typeof import('ant-design-vue/es')['Input']
    AInputNumber: typeof import('ant-design-vue/es')['InputNumber']
    AMenu: typeof import('ant-design-vue/es')['Menu']
    AMenuItem: typeof import('ant-design-vue/es')['MenuItem']
    APagination: typeof import('ant-design-vue/es')['Pagination']
    ARangePicker: typeof import('ant-design-vue/es')['RangePicker']
    ASelect: typeof import('ant-design-vue/es')['Select']
    ASlider: typeof import('ant-design-vue/es')['Slider']
    ASpace: typeof import('ant-design-vue/es')['Space']
    ASwitch: typeof import('ant-design-vue/es')['Switch']
    ATable: typeof import('ant-design-vue/es')['Table']
    ATextarea: typeof import('ant-design-vue/es')['Textarea']
    ATree: typeof import('ant-design-vue/es')['Tree']
    ATreeSelect: typeof import('ant-design-vue/es')['TreeSelect']
    DragModal: typeof import('./src/components/dragModal.vue')['default']
    FrownFilled: typeof import('@ant-design/icons-vue')['FrownFilled']
    FrownOutlined: typeof import('@ant-design/icons-vue')['FrownOutlined']
    MarsuiMarsbutton: typeof import('./src/components/mars-ui/mars-button/index.vue')['default']
    MarsuiMarscolor: typeof import('./src/components/mars-ui/mars-color/index.vue')['default']
    MarsuiMarsdatepicker: typeof import('./src/components/mars-ui/mars-date-picker/index.vue')['default']
    MarsuiMarsdialog: typeof import('./src/components/mars-ui/mars-dialog/index.vue')['default']
    MarsuiMarsgui: typeof import('./src/components/mars-ui/mars-gui/index.vue')['default']
    MarsuiMarsicon: typeof import('./src/components/mars-ui/mars-icon/index.vue')['default']
    MarsuiMarsinput: typeof import('./src/components/mars-ui/mars-input/index.vue')['default']
    MarsuiMarsinputgroup: typeof import('./src/components/mars-ui/mars-input-group/index.vue')['default']
    MarsuiMarsinputnumber: typeof import('./src/components/mars-ui/mars-input-number/index.vue')['default']
    MarsuiMarsrangepicker: typeof import('./src/components/mars-ui/mars-range-picker/index.vue')['default']
    MarsuiMarsselect: typeof import('./src/components/mars-ui/mars-select/index.vue')['default']
    MarsuiMarsslider: typeof import('./src/components/mars-ui/mars-slider/index.vue')['default']
    MarsuiMarsswitch: typeof import('./src/components/mars-ui/mars-switch/index.vue')['default']
    MarsuiMarstable: typeof import('./src/components/mars-ui/mars-table/index.vue')['default']
    MarsuiMarstextarea: typeof import('./src/components/mars-ui/mars-textarea/index.vue')['default']
    MarsworkMainView: typeof import('./src/components/mars-work/main-view.vue')['default']
    MarsworkMarsMap: typeof import('./src/components/mars-work/mars-map.vue')['default']
    MarsworkWidget: typeof import('./src/components/mars-work/widget.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SmileOutlined: typeof import('@ant-design/icons-vue')['SmileOutlined']
    Spin: typeof import('./src/components/spin.vue')['default']
    UiGate: typeof import('./src/components/ui/gate.vue')['default']
    UiTree: typeof import('./src/components/ui/tree/index.vue')['default']
  }
}
